---
- name: common setup
  hosts: k3s_cluster
  become: true
  roles:
    - common
  
- name: install k3s cluster
  import_playbook: k3s.orchestration.site

- name: bootstrap argo
  hosts: server
  become: true
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
  roles:
    - argocd



# set local kubeconfig to point to the server
- name: Fetch kubeconfig from server
  hosts: server
  become: true
  gather_facts: false
  tasks:
    - name: Fetch kubeconfig file
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ lookup('env', 'HOME') }}/.kube/config"
        flat: yes
      run_once: true
- name: Set kubeconfig locally
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Set kubeconfig to use server ip
      ansible.builtin.replace:
        path: "{{ lookup('env', 'HOME') }}/.kube/config"
        regexp: 'https://127\.0\.0\.1:6443'
        replace: "https://{{ groups['server'][0] }}:6443"

