---
# install helm
- name: Download Helm command line tool
  ansible.builtin.uri:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    return_content: true
  register: helm_installer

- name: Install Helm
  ansible.builtin.command:
    cmd: bash
    stdin: "{{ helm_installer.content }}"
    creates: /usr/local/bin/helm
  environment:
    DESIRED_VERSION: "{{ helm_version | default('') }}"

# setup argocd
- name: Add Argo CD Helm repository
  kubernetes.core.helm_repository:
    name: argo
    repo_url: "{{ argocd_helm_repo }}"
    state: present

- name: Clone gitops repo for helm values
  ansible.builtin.git:
    repo: "{{ gitops_repo }}"
    dest: "{{ local_clone_path }}"
    version: "{{ gitops_repo_branch }}"
    force: true 

- name: argocd namespace
  kubernetes.core.k8s:
    name: "{{ argocd_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Deploy argocd
  kubernetes.core.helm:
    name: "{{ argocd_release_name }}"
    chart_ref: argo/argo-cd
    chart_version: "{{ argocd_chart_version }}"
    release_namespace: "{{ argocd_namespace }}"
    create_namespace: true
    # values: "{{ lookup('template', local_clone_path + '/' + argocd_values_file_path) | from_yaml }}"
    values_files:
      - "{{ local_clone_path }}/{{ argocd_values_file_path }}"
    wait: true
    timeout: 5m


