---
- name: install packages
  ansible.builtin.apt:
    name:
      - openssh-server
      - python3-pip
      - curl
      - git
      - python3-kubernetes
    state: present
    update_cache: true
  become: true

- name: enable ssh
  ansible.builtin.systemd:
    name: ssh
    enabled: true
    state: started

- name: allow ssh in firewall
  community.general.ufw:
    rule: allow
    name: OpenSSH
    comment: Allow SSH connections
